apiVersion: v1
data:
    auth: ENC[AES256_GCM,data:HsRX0jhiRx1zavwsyaQdyB/2UDQErQ6cwSMwcUlKfsuvIddUftggCdhuyd0yoUWFjxPVfLJUaRZSdtByh7OK9w==,iv:0EEn2PwyHinNzHtRPz9JHPH1dqWsWEbrMH8sNRt1J1c=,tag:ZgZzj7I5302QtwJkcG2u9Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: generic-basic-auth
    namespace: monitoring
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/eab03aa9-c5da-4c1b-807b-686aed83fb2c
          created_at: "2022-03-21T03:33:25Z"
          enc: AQICAHj0qDpfgO9wb8Ne63a0VPqmK07P9Pqm4dt4axNmrKd7LAEknRicdCjrbQYRBWiGnNhqAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMC1Db1sQcbSafwjx5AgEQgDsBZplkkRa/1Be3mOfzQxeYvvDdzzDSCIxN+51pP96tg3W9HfAVGyCA7B0HIb5+5pROntJLNlu+XB8Q/w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-03-21T03:33:25Z"
    mac: ENC[AES256_GCM,data:cfRwWb3TitODAtMCRS2XrbjcJt/xUu9F/k7lXaDGoKTFYsd7vIs6AclXwnXSi+CKa5FPyDWGtBEZQXkZUc8JWUuoT6nl1oLE9RIhHO1CFGdTDvrLUdvULioFMmv0Mqijr5lez1VDD/PXW1zdAidiGi4gGnqSwg86XBn9hfncE/Y=,iv:2S21uEBNyEGBFUiwsF1rSo39hjswx+49PM1gylwcJsg=,tag:0w4zFD9RAvAvO60s+WF1NQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
