apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: slack-error
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: '*'
      namespace: 'flux-system'
    - kind: Kustomization
      name: '*'
      namespace: 'flux-system'
    - kind: HelmRelease
      name: '*'
      namespace: 'cert-manager'
    - kind: Kustomization
      name: '*'
      namespace: 'cert-manager'
    - kind: HelmRelease
      name: '*'
      namespace: 'kube-system'
    - kind: Kustomization
      name: '*'
      namespace: 'kube-system'
    - kind: HelmRelease
      name: '*'
      namespace: 'ingress'
    - kind: Kustomization
      name: '*'
      namespace: 'ingress'
    - kind: HelmRelease
      name: '*'
      namespace: 'monitoring'
    - kind: Kustomization
      name: '*'
      namespace: 'monitoring'
