apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  values:
    tcp:
      "27017": "alpha/documentdb-proxy:27017"
      "27018": "dev/documentdb-proxy:27017"