apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  releaseName: loki
  targetNamespace: loki
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
