apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespaces
  - ../base/sources
  - ../base/aws-ebs-csi-driver
  - ../base/cert-manager
  - ../base/cluster-autoscaler
  - ../base/external-dns
  - ../base/metrics-server
  - ../base/ingress-nginx
  - ../base/kube-prometheus-stack
  - ./eks-authz-dev
  - ./eks-authz-alpha
#  - ../base/kube-prometheus-stack-v19
  - ../base/loki
patchesStrategicMerge:
  - monitoring/patch-ingress.yaml
  - monitoring/patch-alertmanager-config.yaml
patchesJson6902:
  - path: patch-clusterName.yaml
    target:
      group: helm.toolkit.fluxcd.io
      kind: HelmRelease
      name: cluster-autoscaler
      version: v2beta1
