apiVersion: v1
data:
    address: ENC[AES256_GCM,data:YKKQ0ehuVTaN+FnZIviAvegufmII5RqI4lCIpsEYMnFSoSozzb0XMewPEIooHpVLiNIyc2TlJA5h3Q7eW/MDLBkYht3K+XDV8yK2Z8xWKzet7Lpv6BVxzdDKImX3ZItXmkReLkQiHWof8Zh+,iv:811t6oQCrP5Z6O9X2/zIAiF12Yt6xO1rVaoiMyU/3nc=,tag:PseYg9xHwr/jNuMOzDnoPg==,type:str]
kind: Secret
metadata:
    name: slack-webhook
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/eab03aa9-c5da-4c1b-807b-686aed83fb2c
          created_at: "2021-12-09T19:47:11Z"
          enc: AQICAHj0qDpfgO9wb8Ne63a0VPqmK07P9Pqm4dt4axNmrKd7LAHs7cM3m0nCzsN5sfNr68AwAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMzpgE86JV++/6eDpnAgEQgDunUebSVpIM0UojSYZ7xddKsnV3MOQTUrKzE4k9Sd9iXUbCY0h+4fG748A/dGY42ClDAl5EIerT2KEs+w==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-09T19:47:11Z"
    mac: ENC[AES256_GCM,data:pNnn2Tn63Odz3HP2Kc4ylbZGLMnZKkYiLC3zYmqW75jVK/Ra+TgH2meRcmPXsKrfAlNL1qwx6/f2fEdbSsRiK2YhlfL1zTTIsQz919Pd1rTKosf6icI80kixY/ilYqcKfvJ/OcHWarLavnqhIHYVjRoZUJj4kIZhPn9wHXCkG3s=,iv:+uhHSs8OZuU10aU4atR20xjT+Pn4yaB9vbNBeS+cVLI=,tag:Z+2sJTiopwkAPzoLt13upQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
