---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: eks-app
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: eks-app
  url: ssh://git@github.com/UniverseXYZ/kek-infrastructure-eks-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: eks-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/prod.i.universe.xyz
  prune: true
  sourceRef:
    kind: GitRepository
    name: eks-app
  validation: client
  decryption:
    provider: sops
