apiVersion: kustomize.config.k8s.io/v1beta2
kind: Kustomization
namespace: flux-system
resources:
  - secret-slack-webhook.yaml
  - slack-provider.yaml
  - slack-alert-info.yaml
  - slack-alert-error.yaml
