apiVersion: v1
data:
    address: ENC[AES256_GCM,data:gBWmlAT9kvQnFNPOnzMralb/76naw9t6XFR9T96nEYLCiqCXZA/lrsnbFJGp3H9SGTsT6KVPT85/3GVpQdcsEt6Rk4bQlP/9OFQMVTS3LmH3kcjkIyF36fS9oVKI7o/rLtk2nVWF3779F+5C,iv:a0v7VuWFk4E4bKXX6oyuKJ4YuUaA+qQvlHNJ8yMImLs=,tag:/VryVTgHdfNVLOcFNV/Kew==,type:str]
kind: Secret
metadata:
    name: slack-webhook
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:076129510628:key/f019707e-98d5-454b-adcd-a4b8ccc35f44
          created_at: "2021-12-09T18:42:19Z"
          enc: AQICAHicCjtoxmBmz2MO3QTlS3370ieytvfowEbSDe18IeRxZAHbS/BGCQmfDewYN0Aggbj9AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM0V8F4wizckerWtheAgEQgDvKqtJrknafhssw1nMx1O4K9/IYCIBvmswp6KMdnEgfMNsDkJIOInUFw+Df+1QdgSZJ+l7iPh5qguaeLg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-12-09T18:42:20Z"
    mac: ENC[AES256_GCM,data:IdyaCDMH/sGmfKPEwl5gnvCx6Utu847pA7x+M3So5FvDvgz9eGe+dXw+T5jedPEHiK7Wph1/PV58kwYKV90rUO+L4qLzVQiPJ/ewMvlmDEeEnJN8nL1lab/sS9TfPoHyAmpNxOabNDgQ98wk5x3jEEtBVyafSOZIeYTD3xN8W8M=,iv:CoFvPVhs72pKEpKTulsNUi1s2iPkmqFmgGjQaBLLEbM=,tag:ll1g4mvKgb3uiPgGDZN1qw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
