apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: external-developers
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  verbs:
  - get
  - list
  - describe
  - watch
  - exec
- apiGroups:
  - '*'
  resources:
  - pods/exec
  - pods/logs
  - pods/portforward
  - services/portforward
  verbs:
  - create
