apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: external-developers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: external-developers
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: external-developers
