apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/namespaces
  - ../base/sources
  - ../base/aws-ebs-csi-driver
  - ../base/cert-manager
  - ../base/external-dns
  - ../base/metrics-server
  - ../base/ingress-nginx
  - ../base/kube-prometheus-stack
patchesStrategicMerge:
  - monitoring/patch-ingress.yaml
  - monitoring/patch-alertmanager-config.yaml
