apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: kube-system
spec:
  releaseName: aws-ebs-csi-driver
  targetNamespace: kube-system
  interval: 5m
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: 0.10.1
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
        namespace: flux-system
  values:
    enableVolumeScheduling: true
    enableVolumeResizing: true
    enableVolumeSnapshot: true
    region: us-east-1
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
    storageClasses:
      - name: ebs-sc
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
        volumeBindingMode: WaitForFirstConsumer
        reclaimPolicy: Retain
        parameters:
          encrypted: "true"
