apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base/eks-authz/
patchesJson6902:
  - path: patch-role.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: external-developers
  - path: patch-rolebinding.yaml
    target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: external-developers
